# Generated by Django 2.2.1 on 2019-08-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_cube_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visibledimension',
            name='pcv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='visible_dimensions', to='process_cube_view.ProcessCubeView'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visibledimension',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_cube.Dimension'),
        ),
    ]
