# Generated by Django 2.2.1 on 2019-08-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_cube', '__first__'),
        ('process_cube_view', '0002_auto_20190806_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcubeview',
            name='pcs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='process_cube.ProcessCubeStructure'),
            preserve_default=False,
        ),
    ]
