# Generated by Django 2.2.1 on 2019-08-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventLogAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('case_attribute', models.BooleanField()),
                ('db_query', models.CharField(max_length=255)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_log.EventLog')),
            ],
        ),
        migrations.CreateModel(
            name='EventBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_logs', models.ManyToManyField(to='event_log.EventLog')),
            ],
        ),
    ]
